name: Publish to npm

on:
  release:
    types: [published]

jobs:
  npm-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Publish to npm 🚀
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
